### ISSUE TITLE
Assertion error queue_identifier in self._queueids_to_queues

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2879]
## Problem Definition

While running [this scenario](https://gist.github.com/ulope/0745752b315831dde5bfdab5f659eb1a#file-hanging-test-yaml) One node failed to restart after a few start-transfer-stop cycles [with this error](https://gist.github.com/ulope/0745752b315831dde5bfdab5f659eb1a#file-node-2-log)

So far I haven't seen it reproduced again with more runs, but it suggests that there is a race condition in the state handling somewhere.

### System Description

```
{
  "raiden": "0.14.1.dev27+ga4e934c8.d20181024",
  "python_implementation": "CPython",
  "python_version": "3.6.6",
  "system": "macOS 10.14 64bit",
  "distribution": "source"
}
```

**Comment by palango** [comment]
I saw the same thing when running Ulos scenario.

**Comment by LefterisJP** [comment]
@palango or @ulope can one you look further into this? Debug the node where the assertion happens to get more information on what can be wrong?

(if you work on this assign yourself please)

**Comment by ulope** [comment]
It's likely this may  be fixed by #2889 / #2948

**Comment by konradkonrad** [comment]
@ulope 

running #2570 (or its related PR) on top of #2948 I can still see the assertion errors for `assert queue_identifier in self._queueids_to_queues`

**Comment by ulope** [comment]
@konradkonrad Thanks! Does it only happen when running on top of #2948?

**Comment by konradkonrad** [comment]
no, I tested on top of 2948, because I saw the error and your suggestion in this issue

**Comment by ulope** [comment]
Ok thanks.

**Comment by konradkonrad** [comment]
cannot reproduce anymore on latest master f3f9facbbc6550e9aadd291a8eb565f3c225fbce
