### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#3244]
<!--## Intro

Raiden crashed with exception - tuple index out of range

Attached logs
[raiden-debug_2019-01-09T12_28_17.240624.log](https://github.com/raiden-network/raiden/files/2741200/raiden-debug_2019-01-09T12_28_17.240624.log)
[raiden-exception-2019-01-09T12-28efhkju6l.txt](https://github.com/raiden-network/raiden/files/2741201/raiden-exception-2019-01-09T12-28efhkju6l.txt)

**Comment by LefterisJP** [comment]
@offerm can you provide some more info on what happened here? What exactly did you do to get this error, provide a stack trace e.t.c.?

**Comment by calinchiper** [comment]
I get error using a private ethereum node.
What I did:
1) I created my private network using geth
2) Deployed Raiden contracts
3) Started the raiden script and referenced all the deployed contracts
`./raiden --keystore-path ~/blockchain/private/keystore/ --tokennetwork-registry-contract-address 0xeb51da6085659c9cBE2241E32A4C60572af8c6c1 --secret-registry-contract-address 0x0435ae45bc66Df745Ad30C665fe68dF82fd84f2F --endpoint-registry-contract-address 0x3748d6bd3A8cAE08355A2A901cCb906247aAf441 --console --network-id 4224 --no-sync-check`

First time it worked fine, but then I restarted raiden and geth. Now the error persists when I use raiden.

Traceback:

Traceback (most recent call last):
  File "site-packages/raiden/ui/runners.py", line 178, in _start_services
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "site-packages/gevent/_compat.py", line 47, in reraise
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "site-packages/raiden/tasks.py", line 73, in check_gas_reserve
  File "site-packages/raiden/utils/gas_reserve.py", line 144, in has_enough_gas_reserve
  File "site-packages/raiden/utils/gas_reserve.py", line 120, in get_reserve_estimate
  File "site-packages/raiden/network/rpc/client.py", line 346, in gas_price
  File "site-packages/web3/eth.py", line 385, in generateGasPrice
  File "site-packages/web3/gas_strategies/time_based.py", line 168, in time_based_gas_price_strategy
  File "site-packages/web3/gas_strategies/time_based.py", line 104, in _compute_gas_price
IndexError: tuple index out of range

**Comment by rakanalh** [comment]
@calinchiper I think this is an issue that has been fixed here: https://github.com/raiden-network/raiden/pull/2988/

While we don't recommend using latest master to run Raiden, you're using a private chain which i think should be fine in your case (But don't run latest master on mainnet, please wait for a newer release to include the fixes).

Please report back if the issue is fixed on latest master once you run it, and if that's the case, feel free to close the issue.

**Comment by calinchiper** [comment]
I will look after it this week.

**Comment by offerm** [comment]
@rakanalh I'm still having this issue. Using a private chain as @calinchiper .

```
2019-02-05 11:29:29.128501 [info     ] Starting Raiden                [raiden.ui.runners] distribution=source python_implementation=CPython python_version=3.7.2 raiden=0.100.2rc4.dev129+gd50045c7.d20190203 system=macOS 10.14 64bit
2019-02-05 11:29:33.147221 [error    ] no upnp providers found        [raiden.network.upnpsock] 
2019-02-05 11:29:50.799153 [info     ] Network port opened            [raiden.network.sockfactory] external=95.210.21.92:39004 internal=0.0.0.0:38647 method=stun
Raiden is running in development mode

You are connected to the '4321' network and the DB path is: /Users/admin/xud-eth/exchange-a/node_b9a2c5e9/netid_4321/network_ec5ac45e/v17_log.db
Traceback (most recent call last):
  File "/Users/admin/.virtualenvs/raiden/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/Users/admin/raiden/raiden/__main__.py", line 11, in main
    run(auto_envvar_prefix='RAIDEN')  # pylint: disable=no-value-for-parameter
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/admin/raiden/raiden/ui/cli.py", line 439, in run
    app = runner.run()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 235, in run
    app = self._start_services()
  File "/Users/admin/raiden/raiden/ui/runners.py", line 96, in _start_services
    app_ = run_app(**self._options)
  File "/Users/admin/raiden/raiden/ui/app.py", line 386, in run_app
    endpoint_registry_contract_address,
  File "/Users/admin/raiden/raiden/ui/app.py", line 117, in _setup_udp
    check_discovery_registration_gas(blockchain_service, address)
  File "/Users/admin/raiden/raiden/ui/sync.py", line 57, in check_discovery_registration_gas
    discovery_tx_cost = blockchain_service.client.gas_price() * GAS_REQUIRED_FOR_ENDPOINT_REGISTER
  File "/Users/admin/raiden/raiden/network/rpc/client.py", line 479, in gas_price
    price = int(self.web3.eth.generateGasPrice())
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/eth.py", line 385, in generateGasPrice
    return self.gasPriceStrategy(self.web3, transaction_params)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/gas_strategies/time_based.py", line 168, in time_based_gas_price_strategy
    gas_price = _compute_gas_price(probabilities, probability / 100)
  File "/Users/admin/.virtualenvs/raiden/lib/python3.7/site-packages/web3/gas_strategies/time_based.py", line 104, in _compute_gas_price
    first = probabilities[0]
IndexError: tuple index out of range
```

Let me know if you need any other info.

**Comment by calinchiper** [comment]
The error still persists. @offerm  What's your raiden version?

**Comment by calinchiper** [comment]
@rakanalh @LefterisJP Is any ways to bypass this error. It's very strange because it worked just one time.

**Comment by offerm** [comment]
Im using the master.

**Comment by LefterisJP** [comment]
> @calinchiper I think this is an issue that has been fixed here: #2988

@rakanalh This has nothing to do with gas estimation.

It's another case of web3 gas price strategy having a bug. It's in web3.
We had a similar case with Infura at https://github.com/raiden-network/raiden/issues/3201 with a fix done [here](https://github.com/raiden-network/raiden/commit/0360d215ded4627104a6e0616e8e41bf4f4be282).

---

@offerm @calinchiper 

Hmm so this seems to be yet another way at which the web3 gas price generation can fail. The culprit is `web3.eth.generateGasPrice()` again. Seems to have problems with private testnets (perhaps).

Can you guys provide us with a reproducible step-by-step scenario of how you run the private testnet so we can debug this.

The fix is to probably also catch the `IndexError` at the same place as [this commit](https://github.com/raiden-network/raiden/commit/0360d215ded4627104a6e0616e8e41bf4f4be282) did but I don't want to make code changes without having a test to see if they have an effect.

**Comment by LefterisJP** [comment]
Another workaround is to provide the gas price manually as an argument when you start raiden by adding: `--gas-price 10000000000` for say 10 gwei. This will enforce a fixed gas price across raiden and override the other gas price strategies.

**Comment by offerm** [comment]
@LefterisJP `--gas-price 10000000000` is a workaround. Many thanks.

I will try to document how to reproduce the issue with a private chain. Should not be that complicated - just need to find the time.

**Comment by offerm** [comment]
@LefterisJP  So here is how to reproduce (you may need to make local changes....) :
- install geth
- install raiden-contracts (I'm using commit 7176ceec2e05f359964b89e8d4a9564f7f54b4c4 of master)
- install raiden
- create a directory xud-eth under your home 

In shell 1:
- create genesis.json file in xud-eth (take from the attached zip)
- generate init by `geth --datadir blkchain1 init genesis.json `
- start `geth` with `geth --rpc --datadir blkchain1  --networkid 4321 --rpcapi "eth,net,web3,txpool" console`
- create an account `>personal.newAccount()` enter a passphrase when needed (and remember it)
- start mining with `>miner.start()`
 In shell 2:
-define $private_key with `export private_key=/Users/admin/xud-eth/blkchain1/keystore/UTC--   xxxxxxx` use auto complete to complete the file name 
- use the `bash deploy.sh` file to create the contracts and token. Note that you will be asked to provide the passphrase 3 times. If you make a mistake you would need to restart. 
At the end of the execution take a note of 
```
{
    "EndpointRegistry": "0x8DA4d7B914f53719d59D7eC69E7F5E647Fe90E5a",
    "SecretRegistry": "0x6dA7a0c026368a75b412206e8D7572306A243e7B",
    "TokenNetworkRegistry": "0xbc40CC650a23b442AFAEc98c84B416bA1Eab6f16"
}

and

CustomToken=0x17cAC640B260d90BE2b102cEAf3f893026956771
```

create a file `passwd_file` and place in it the passphrase of the account. This is needed by raiden start command that we are going to use

- edit the file `raiden-a.bash` and replace the values in the first 5 lines with the values you got from the deploy.bash script. To get the value for `address` you can restart `geth` and use the value shown in the line `INFO [02-12|16:48:05.266] Etherbase automatically configured       address=`. 
Don't forget to start mining with `>miner.start()`

- run `bash raiden-a.bash`. A few seconds after starting properly you should see this:
```
Python 3.7.2 (default, Jan 13 2019, 12:50:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: FATAL: An unexpected exception occured. A traceback has been written to /var/folders/06/5x3r2f911slcdg34vqnt058h0000gn/T/raiden-exception-2019-02-12T15-1591fwfhts.txt
tuple index out of range
```


if you add to `raiden-a.bash` the `--gas-price 10000000000` you will not face the problem.

[files.zip](https://github.com/raiden-network/raiden/files/2856415/files.zip)

**Comment by pirapira** [comment]
@offerm on `raiden:master` == 23114972c922fa08ebdecfc506941c417895c03d I tried your `deploy.sh` and `raiden-a.bash`.  I didn't see the `FATAL` error anymore.  Will you try?

**Comment by pirapira** [comment]
```
In [1]: FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2019-03-28T16-33_0sye_yl.txt
tuple index out of range
```

**Comment by pirapira** [comment]
The saved traceback contains:

```
Traceback (most recent call last):
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/raiden/ui/runners.py", line 179, in _start_services
    event.get()
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 409, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/raiden/tasks.py", line 75, in check_gas_reserve
    channels_to_open=1,
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/raiden/utils/gas_reserve.py", line 144, in has_enough_gas_reserve
    secure_reserve_estimate = get_reserve_estimate(raiden, channels_to_open)
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/raiden/utils/gas_reserve.py", line 120, in get_reserve_estimate
    gas_price = raiden.chain.client.gas_price()
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 479, in gas_price
    price = int(self.web3.eth.generateGasPrice())
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/web3/eth.py", line 385, in generateGasPrice
    return self.gasPriceStrategy(self.web3, transaction_params)
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/web3/gas_strategies/time_based.py", line 168, in time_based_gas_price_strategy
    gas_price = _compute_gas_price(probabilities, probability / 100)
  File "/home/yoichi/.virtualenvs/raiden/lib/python3.7/site-packages/web3/gas_strategies/time_based.py", line 104, in _compute_gas_price
    first = probabilities[0]
IndexError: tuple index out of range
/tmp/raiden-exception-2019-03-28T16-33_0sye_yl.txt
```

**Comment by pirapira** [comment]
I'm more or less sure that the issue is https://github.com/ethereum/web3.py/issues/1149 .   The chain contains no transactions.

**Comment by pirapira** [comment]
Web3.py [doesn't seem to](https://github.com/ethereum/web3.py/issues/1149#issuecomment-446349451) fix this soon.  So `raiden` has to do something about it.

**Comment by pirapira** [comment]
I'll file a PR and ask @LefterisJP to review it.

**Comment by LefterisJP** [comment]
I am here for a review @pirapira whenever you need :heart:

**Comment by pirapira** [comment]
I was testing an older version not `master`.  So I don't know if the issue is still there.

**Comment by pirapira** [comment]
On `master` I see #3687 so I cannot test this issue.

**Comment by pirapira** [comment]
I'll try to reproduce this again (#3687 should be already fixed).

**Comment by pirapira** [comment]
On `master` I see https://github.com/raiden-network/raiden-contracts/issues/795 so I cannot test this issue.

**Comment by pirapira** [comment]
@offerm On `raiden:master` I was able to start the Raiden client on a private chain.  I was not able to see `tuple index out of rande`.  Can you reproduce the `tuple index out of range` on `raiden:master`?

**Comment by pirapira** [comment]
Now I'm able to reproduce this issue on 8d5756ba48954abeca423bf838bece0f4d59d303 (`master` today).

**Comment by pirapira** [comment]
This is how I can reproduce the issue https://github.com/raiden-network/raiden/blob/fe45769dd3c3f339b30a214599d028eb8351dc6a/docs/private_net_tutorial.rst

**Comment by pirapira** [comment]
The guide works when https://github.com/raiden-network/raiden/pull/3810 is merged.

**Comment by offerm** [comment]
You managed to reproduce?

you should not provide gas limit

**Comment by pirapira** [comment]
Yeah, I managed to reproduce.  I posted a wrong link:  https://github.com/pirapira/raiden/blob/be088c233293d7b02fc55e7549950f4da03fe2e3/docs/private_net_tutorial.rst
