### ISSUE TITLE
Resync state between channel partners

### ISSUE THREAD

**Issue by heikoheiko** [raiden-network/raiden#79]
two clients could be in a different state if transfer or secret messages are not received.

**Comment by utzig** [comment]
This was most probably fixed by #104

**Comment by hackaugusto** [comment]
#104 doesnt fix ordering problems with `secret` messages, because that involves a variable number of nodes that are not controlled by who is sending the message. The message ordering is only useful for network problems that happen between these two imediate nodes.

**Comment by heikoheiko** [comment]
can you elaborate what the ordering problems with secret messages is?

**Comment by hackaugusto** [comment]
With a channel between alice and bob, alice sends one first mediated transfer to bob, bob receives the secret from charlie, before bob tells alice that he received a secret she sends a new message, since alice didn't claim the lock but bob did the locksroot don't match, so bob discards the transfer.

This doesnt just incur into additional latency, retries wont make bob accept the transfer, we need to recompute the locksroot with the given lock claimed for the given transfer and all others waiting in the queue.

**Comment by heikoheiko** [comment]
yes, we need sync on the looks_root. 
one solution would be, that the sending side triggers the update of the locks_root. e.g. in above case Bob would forward the secret to Alice but not apply it yet. Alice applies it and sends a message to Bob notifying this.

**Comment by hackaugusto** [comment]
#104 and 05e79d9eda8f850a019893432ba12d78c2de07bf fixed it.

> Only claim the lock once the secret is sent back from the mediated
transfer sender, this allows the sender to synchronize the partner
changes into the merkleroot
